package ru.netology

data class Post(
    val id: Long?,
    val ownerId: Long,
    val fromId: Long,
    val createdBy: Long?,
    val date: Int,
    val text: String,
    val replyOwnerId: Long,
    val replyPostId: Long?,
    val friendsOnly: Boolean,
    val comments: Comments?,
    val copyright: String?,
    val likes: Likes?,
    val reposts: Reposts?,
    val views: Views?,
    val postType: String,
    val postSource: PostSource?,
    val geo: Geo?,
    val signerId: Long,
    val copyHistory: String?,
    val canPin: Boolean,
    val canDelete: Boolean,
    val canEdit: Boolean,
    val isPinned: Boolean,
    val markedAsAds: Boolean,
    val isFavourite: Boolean,
    val postponedId: Int
)
